#!/bin/bash -l
#SBATCH -J bsimds_TIGRESS_ts_001
#SBATCH -t 2-00:00:00
#SBATCH -N 10
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=128
#SBATCH -p batch
#SBATCH --no-requeue

cd /home/users/ttong/TIGRESS
conda activate TIGRESS

srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered Rscript run.R --save-folder="/home/users/ttong/TIGRESS/results/20230516_10ts_001" --b-time-steps=10 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims15r1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered Rscript run.R --save-folder="/home/users/ttong/TIGRESS/results/20230516_10ts_001" --b-time-steps=10 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims15r2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered Rscript run.R --save-folder="/home/users/ttong/TIGRESS/results/20230516_10ts_001" --b-time-steps=10 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims15r3.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered Rscript run.R --save-folder="/home/users/ttong/TIGRESS/results/20230516_10ts_001" --b-time-steps=10 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims30r1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered Rscript run.R --save-folder="/home/users/ttong/TIGRESS/results/20230516_10ts_001" --b-time-steps=10 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims30r2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered Rscript run.R --save-folder="/home/users/ttong/TIGRESS/results/20230516_10ts_001" --b-time-steps=10 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims30r3.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered Rscript run.R --save-folder="/home/users/ttong/TIGRESS/results/20230516_10ts_001" --b-time-steps=10 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims50r1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered Rscript run.R --save-folder="/home/users/ttong/TIGRESS/results/20230516_10ts_001" --b-time-steps=10 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims50r2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered Rscript run.R --save-folder="/home/users/ttong/TIGRESS/results/20230516_10ts_001" --b-time-steps=10 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims50r3.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered Rscript run.R --save-folder="/home/users/ttong/TIGRESS/results/20230516_10ts_001" --b-time-steps=10 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims100r1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered Rscript run.R --save-folder="/home/users/ttong/TIGRESS/results/20230516_10ts_001" --b-time-steps=10 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims100r2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered Rscript run.R --save-folder="/home/users/ttong/TIGRESS/results/20230516_10ts_001" --b-time-steps=10 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims100r3.npy" &

srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered Rscript run.R --save-folder="/home/users/ttong/TIGRESS/results/20230516_20ts_001" --b-time-steps=20 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims15r1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered Rscript run.R --save-folder="/home/users/ttong/TIGRESS/results/20230516_20ts_001" --b-time-steps=20 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims15r2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered Rscript run.R --save-folder="/home/users/ttong/TIGRESS/results/20230516_20ts_001" --b-time-steps=20 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims15r3.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered Rscript run.R --save-folder="/home/users/ttong/TIGRESS/results/20230516_20ts_001" --b-time-steps=20 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims30r1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered Rscript run.R --save-folder="/home/users/ttong/TIGRESS/results/20230516_20ts_001" --b-time-steps=20 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims30r2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered Rscript run.R --save-folder="/home/users/ttong/TIGRESS/results/20230516_20ts_001" --b-time-steps=20 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims30r3.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered Rscript run.R --save-folder="/home/users/ttong/TIGRESS/results/20230516_20ts_001" --b-time-steps=20 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims50r1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered Rscript run.R --save-folder="/home/users/ttong/TIGRESS/results/20230516_20ts_001" --b-time-steps=20 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims50r2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered Rscript run.R --save-folder="/home/users/ttong/TIGRESS/results/20230516_20ts_001" --b-time-steps=20 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims50r3.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered Rscript run.R --save-folder="/home/users/ttong/TIGRESS/results/20230516_20ts_001" --b-time-steps=20 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims100r1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered Rscript run.R --save-folder="/home/users/ttong/TIGRESS/results/20230516_20ts_001" --b-time-steps=20 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims100r2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered Rscript run.R --save-folder="/home/users/ttong/TIGRESS/results/20230516_20ts_001" --b-time-steps=20 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims100r3.npy" &

srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered Rscript run.R --save-folder="/home/users/ttong/TIGRESS/results/20230516_30ts_001" --b-time-steps=30 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims15r1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered Rscript run.R --save-folder="/home/users/ttong/TIGRESS/results/20230516_30ts_001" --b-time-steps=30 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims15r2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered Rscript run.R --save-folder="/home/users/ttong/TIGRESS/results/20230516_30ts_001" --b-time-steps=30 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims15r3.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered Rscript run.R --save-folder="/home/users/ttong/TIGRESS/results/20230516_30ts_001" --b-time-steps=30 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims30r1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered Rscript run.R --save-folder="/home/users/ttong/TIGRESS/results/20230516_30ts_001" --b-time-steps=30 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims30r2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered Rscript run.R --save-folder="/home/users/ttong/TIGRESS/results/20230516_30ts_001" --b-time-steps=30 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims30r3.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered Rscript run.R --save-folder="/home/users/ttong/TIGRESS/results/20230516_30ts_001" --b-time-steps=30 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims50r1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered Rscript run.R --save-folder="/home/users/ttong/TIGRESS/results/20230516_30ts_001" --b-time-steps=30 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims50r2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered Rscript run.R --save-folder="/home/users/ttong/TIGRESS/results/20230516_30ts_001" --b-time-steps=30 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims50r3.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered Rscript run.R --save-folder="/home/users/ttong/TIGRESS/results/20230516_30ts_001" --b-time-steps=30 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims100r1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered Rscript run.R --save-folder="/home/users/ttong/TIGRESS/results/20230516_30ts_001" --b-time-steps=30 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims100r2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered Rscript run.R --save-folder="/home/users/ttong/TIGRESS/results/20230516_30ts_001" --b-time-steps=30 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims100r3.npy" &

srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered Rscript run.R --save-folder="/home/users/ttong/TIGRESS/results/20230516_40ts_001" --b-time-steps=40 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims15r1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered Rscript run.R --save-folder="/home/users/ttong/TIGRESS/results/20230516_40ts_001" --b-time-steps=40 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims15r2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered Rscript run.R --save-folder="/home/users/ttong/TIGRESS/results/20230516_40ts_001" --b-time-steps=40 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims15r3.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered Rscript run.R --save-folder="/home/users/ttong/TIGRESS/results/20230516_40ts_001" --b-time-steps=40 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims30r1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered Rscript run.R --save-folder="/home/users/ttong/TIGRESS/results/20230516_40ts_001" --b-time-steps=40 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims30r2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered Rscript run.R --save-folder="/home/users/ttong/TIGRESS/results/20230516_40ts_001" --b-time-steps=40 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims30r3.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered Rscript run.R --save-folder="/home/users/ttong/TIGRESS/results/20230516_40ts_001" --b-time-steps=40 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims50r1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered Rscript run.R --save-folder="/home/users/ttong/TIGRESS/results/20230516_40ts_001" --b-time-steps=40 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims50r2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered Rscript run.R --save-folder="/home/users/ttong/TIGRESS/results/20230516_40ts_001" --b-time-steps=40 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims50r3.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered Rscript run.R --save-folder="/home/users/ttong/TIGRESS/results/20230516_40ts_001" --b-time-steps=40 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims100r1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered Rscript run.R --save-folder="/home/users/ttong/TIGRESS/results/20230516_40ts_001" --b-time-steps=40 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims100r2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered Rscript run.R --save-folder="/home/users/ttong/TIGRESS/results/20230516_40ts_001" --b-time-steps=40 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims100r3.npy" &


wait
exit

