#!/bin/bash -l
#SBATCH -J bsimds_NL_ODE_003
#SBATCH -t 2-00:00:00
#SBATCH -N 41
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=128
#SBATCH -p batch
#SBATCH --no-requeue

cd /home/users/ttong/GRNs_nonlinear_ODEs
conda activate GRNs_nonlinear_ODEs

srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims15r1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims15r1_n1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims15r1_n2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims15r1_n3.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims15r1_n4.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims15r1_n5.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims15r2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims15r2_n1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims15r2_n2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims15r2_n3.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims15r2_n4.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims15r2_n5.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims15r3.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims15r3_n1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims15r3_n2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims15r3_n3.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims15r3_n4.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims15r3_n5.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims30r1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims30r1_n1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims30r1_n2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims30r1_n3.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims30r1_n4.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims30r1_n5.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims30r2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims30r2_n1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims30r2_n2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims30r2_n3.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims30r2_n4.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims30r2_n5.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims30r3.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims30r3_n1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims30r3_n2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims30r3_n3.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims30r3_n4.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims30r3_n5.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims50r1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims50r1_n1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims50r1_n2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims50r1_n3.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims50r1_n4.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims50r1_n5.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims50r2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims50r2_n1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims50r2_n2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims50r2_n3.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims50r2_n4.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims50r2_n5.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims50r3.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims50r3_n1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims50r3_n2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims50r3_n3.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims50r3_n4.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims50r3_n5.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims100r1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims100r1_n1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims100r1_n2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims100r1_n3.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims100r1_n4.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims100r1_n5.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims100r2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims100r2_n1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims100r2_n2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims100r2_n3.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims100r2_n4.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims100r2_n5.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims100r3.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims100r3_n1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims100r3_n2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims100r3_n3.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims100r3_n4.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="brain_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims100r3_n5.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="food_webs" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims15r1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="food_webs" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims15r2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="food_webs" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims15r3.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="food_webs" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims30r1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="food_webs" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims30r2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="food_webs" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims30r3.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="food_webs" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims50r1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="food_webs" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims50r2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="food_webs" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims50r3.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="food_webs" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims100r1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="food_webs" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims100r2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="food_webs" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims100r3.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="gene_regulatory_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims15r1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="gene_regulatory_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims15r2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="gene_regulatory_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims15r3.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="gene_regulatory_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims30r1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="gene_regulatory_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims30r2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="gene_regulatory_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims30r3.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="gene_regulatory_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims50r1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="gene_regulatory_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims50r2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="gene_regulatory_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims50r3.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="gene_regulatory_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims100r1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="gene_regulatory_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims100r2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="gene_regulatory_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims100r3.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="gene_coexpression_networks" --b-simulation-type="netsims" --b-suffix="test_netsims15r1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="gene_coexpression_networks" --b-simulation-type="netsims" --b-suffix="test_netsims15r2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="gene_coexpression_networks" --b-simulation-type="netsims" --b-suffix="test_netsims15r3.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="gene_coexpression_networks" --b-simulation-type="netsims" --b-suffix="test_netsims30r1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="gene_coexpression_networks" --b-simulation-type="netsims" --b-suffix="test_netsims30r2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="gene_coexpression_networks" --b-simulation-type="netsims" --b-suffix="test_netsims30r3.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="gene_coexpression_networks" --b-simulation-type="netsims" --b-suffix="test_netsims50r1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="gene_coexpression_networks" --b-simulation-type="netsims" --b-suffix="test_netsims50r2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="gene_coexpression_networks" --b-simulation-type="netsims" --b-suffix="test_netsims50r3.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="gene_coexpression_networks" --b-simulation-type="netsims" --b-suffix="test_netsims100r1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="gene_coexpression_networks" --b-simulation-type="netsims" --b-suffix="test_netsims100r2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="gene_coexpression_networks" --b-simulation-type="netsims" --b-suffix="test_netsims100r3.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="man-made_organic_reaction_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims15r1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="man-made_organic_reaction_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims15r2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="man-made_organic_reaction_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims15r3.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="man-made_organic_reaction_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims30r1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="man-made_organic_reaction_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims30r2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="man-made_organic_reaction_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims30r3.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="man-made_organic_reaction_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims50r1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="man-made_organic_reaction_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims50r2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="man-made_organic_reaction_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims50r3.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="man-made_organic_reaction_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims100r1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="man-made_organic_reaction_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims100r2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="man-made_organic_reaction_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims100r3.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="intercellular_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims15r1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="intercellular_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims15r2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="intercellular_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims15r3.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="intercellular_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims30r1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="intercellular_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims30r2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="intercellular_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims30r3.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="intercellular_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims50r1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="intercellular_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims50r2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="intercellular_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims50r3.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="intercellular_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims100r1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="intercellular_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims100r2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="intercellular_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims100r3.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="vascular_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims15r1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="vascular_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims15r2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="vascular_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims15r3.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="vascular_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims30r1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="vascular_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims30r2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="vascular_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims30r3.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="vascular_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims50r1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="vascular_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims50r2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="vascular_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims50r3.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="vascular_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims100r1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="vascular_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims100r2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="vascular_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims100r3.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="reaction_networks_inside_living_organism" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims15r1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="reaction_networks_inside_living_organism" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims15r2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="reaction_networks_inside_living_organism" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims15r3.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="reaction_networks_inside_living_organism" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims30r1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="reaction_networks_inside_living_organism" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims30r2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="reaction_networks_inside_living_organism" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims30r3.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="reaction_networks_inside_living_organism" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims50r1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="reaction_networks_inside_living_organism" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims50r2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="reaction_networks_inside_living_organism" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims50r3.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="reaction_networks_inside_living_organism" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims100r1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="reaction_networks_inside_living_organism" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims100r2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="reaction_networks_inside_living_organism" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims100r3.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="chemical_reaction_networks_in_atmosphere" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims15r1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="chemical_reaction_networks_in_atmosphere" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims15r2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="chemical_reaction_networks_in_atmosphere" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims15r3.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="chemical_reaction_networks_in_atmosphere" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims30r1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="chemical_reaction_networks_in_atmosphere" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims30r2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="chemical_reaction_networks_in_atmosphere" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims30r3.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="chemical_reaction_networks_in_atmosphere" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims50r1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="chemical_reaction_networks_in_atmosphere" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims50r2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="chemical_reaction_networks_in_atmosphere" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims50r3.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="chemical_reaction_networks_in_atmosphere" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims100r1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="chemical_reaction_networks_in_atmosphere" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims100r2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="chemical_reaction_networks_in_atmosphere" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims100r3.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="landscape_networks" --b-simulation-type="netsims" --b-suffix="test_netsims15r1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="landscape_networks" --b-simulation-type="netsims" --b-suffix="test_netsims15r2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="landscape_networks" --b-simulation-type="netsims" --b-suffix="test_netsims15r3.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="landscape_networks" --b-simulation-type="netsims" --b-suffix="test_netsims30r1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="landscape_networks" --b-simulation-type="netsims" --b-suffix="test_netsims30r2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="landscape_networks" --b-simulation-type="netsims" --b-suffix="test_netsims30r3.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="landscape_networks" --b-simulation-type="netsims" --b-suffix="test_netsims50r1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="landscape_networks" --b-simulation-type="netsims" --b-suffix="test_netsims50r2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="landscape_networks" --b-simulation-type="netsims" --b-suffix="test_netsims50r3.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="landscape_networks" --b-simulation-type="netsims" --b-suffix="test_netsims100r1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="landscape_networks" --b-simulation-type="netsims" --b-suffix="test_netsims100r2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="landscape_networks" --b-simulation-type="netsims" --b-suffix="test_netsims100r3.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="social_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims15r1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="social_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims15r2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="social_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims15r3.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="social_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims30r1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="social_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims30r2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="social_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims30r3.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="social_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims50r1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="social_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims50r2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="social_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims50r3.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="social_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims100r1.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="social_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims100r2.npy" &
srun -N 1 -n 1 --cpus-per-task $SLURM_CPUS_PER_TASK --exclusive --unbuffered python run.py --save-folder="/home/users/ttong/GRNs_nonlinear_ODEs/results/20230422_003" --b-time-steps=49 --b-network-type="social_networks" --b-directed --b-simulation-type="netsims" --b-suffix="test_netsims100r3.npy" &

wait
exit
