import os

currt_path = os.getcwd()

bash_list = [
    'train_MPM_LN_15_D_NS_R1.sh',
    'train_MPM_LN_15_D_NS_R2.sh',
    'train_MPM_LN_15_D_NS_R3.sh',
    'train_MPM_MMO_15_D_NS_R1.sh',
    'train_MPM_MMO_15_D_NS_R2.sh',
    'train_MPM_MMO_15_D_NS_R3.sh',
    'train_MPM_RNLO_15_D_NS_R1.sh',
    'train_MPM_RNLO_15_D_NS_R2.sh',
    'train_MPM_RNLO_15_D_NS_R3.sh',
    'train_MPM_SN_15_D_NS_R1.sh',
    'train_MPM_SN_15_D_NS_R2.sh',
    'train_MPM_SN_15_D_NS_R3.sh',
    'train_MPM_VN_15_D_NS_R1.sh',
    'train_MPM_VN_15_D_NS_R2.sh',
    'train_MPM_VN_15_D_NS_R3.sh',
    # 'train_MPM_FW_15_D_NS_R1_seed10.sh',
    # 'train_MPM_FW_15_D_NS_R2_seed10.sh',
    # 'train_MPM_FW_15_D_NS_R3_seed10.sh',
    # 'train_MPM_FW_15_D_NS_R1_seed144.sh',
    # 'train_MPM_FW_15_D_NS_R2_seed144.sh',
    # 'train_MPM_FW_15_D_NS_R3_seed144.sh',
    'train_MPM_LN_15_D_SP_R1.sh',
    'train_MPM_LN_15_D_SP_R2.sh',
    'train_MPM_LN_15_D_SP_R3.sh',
    'train_MPM_MMO_15_D_SP_R1.sh',
    'train_MPM_MMO_15_D_SP_R2.sh',
    'train_MPM_MMO_15_D_SP_R3.sh',
    'train_MPM_RNLO_15_D_SP_R1.sh',
    'train_MPM_RNLO_15_D_SP_R2.sh',
    'train_MPM_RNLO_15_D_SP_R3.sh',
    'train_MPM_SN_15_D_SP_R1.sh',
    'train_MPM_SN_15_D_SP_R2.sh',
    'train_MPM_SN_15_D_SP_R3.sh',
    'train_MPM_VN_15_D_SP_R1.sh',
    'train_MPM_VN_15_D_SP_R2.sh',
    'train_MPM_VN_15_D_SP_R3.sh',
    # 'train_MPM_FW_15_D_SP_R1_seed10.sh',
    # 'train_MPM_FW_15_D_SP_R2_seed10.sh',
    # 'train_MPM_FW_15_D_SP_R3_seed10.sh',
    # 'train_MPM_FW_15_D_SP_R1_seed144.sh',
    # 'train_MPM_FW_15_D_SP_R2_seed144.sh',
    # 'train_MPM_FW_15_D_SP_R3_seed144.sh',
]

# bash_list = [
#     'train_MPM_GCN_30_D_NS_R1.sh',
#     'train_MPM_GCN_30_D_NS_R2.sh',
#     'train_MPM_GCN_30_D_NS_R3.sh',
#     'train_MPM_GRN_30_D_NS_R1.sh',
#     'train_MPM_GRN_30_D_NS_R2.sh',
#     'train_MPM_GRN_30_D_NS_R3.sh',
#     'train_MPM_IN_30_D_NS_R1.sh',
#     'train_MPM_IN_30_D_NS_R2.sh',
#     'train_MPM_IN_30_D_NS_R3.sh',
#     'train_MPM_LN_30_D_NS_R1.sh',
#     'train_MPM_LN_30_D_NS_R2.sh',
#     'train_MPM_LN_30_D_NS_R3.sh',
#     'train_MPM_MMO_30_D_NS_R1.sh',
#     'train_MPM_MMO_30_D_NS_R2.sh',
#     'train_MPM_MMO_30_D_NS_R3.sh',
#     'train_MPM_RNLO_30_D_NS_R1.sh',
#     'train_MPM_RNLO_30_D_NS_R2.sh',
#     'train_MPM_RNLO_30_D_NS_R3.sh',
#     'train_MPM_SN_30_D_NS_R1.sh',
#     'train_MPM_SN_30_D_NS_R2.sh',
#     'train_MPM_SN_30_D_NS_R3.sh',
#     'train_MPM_VN_30_D_NS_R1.sh',
#     'train_MPM_VN_30_D_NS_R2.sh',
#     'train_MPM_VN_30_D_NS_R3.sh',
#     # 'train_MPM_FW_30_D_NS_R1_seed10.sh',
#     # 'train_MPM_FW_30_D_NS_R2_seed10.sh',
#     # 'train_MPM_FW_30_D_NS_R3_seed10.sh',
#     # 'train_MPM_FW_30_D_NS_R1_seed144.sh',
#     # 'train_MPM_FW_30_D_NS_R2_seed144.sh',
#     # 'train_MPM_FW_30_D_NS_R3_seed144.sh',
#     'train_MPM_GCN_30_D_SP_R1.sh',
#     'train_MPM_GCN_30_D_SP_R2.sh',
#     'train_MPM_GCN_30_D_SP_R3.sh',
#     'train_MPM_GRN_30_D_SP_R1.sh',
#     'train_MPM_GRN_30_D_SP_R2.sh',
#     'train_MPM_GRN_30_D_SP_R3.sh',
#     'train_MPM_IN_30_D_SP_R1.sh',
#     'train_MPM_IN_30_D_SP_R2.sh',
#     'train_MPM_IN_30_D_SP_R3.sh',
#     'train_MPM_LN_30_D_SP_R1.sh',
#     'train_MPM_LN_30_D_SP_R2.sh',
#     'train_MPM_LN_30_D_SP_R3.sh',
#     'train_MPM_MMO_30_D_SP_R1.sh',
#     'train_MPM_MMO_30_D_SP_R2.sh',
#     'train_MPM_MMO_30_D_SP_R3.sh',
#     'train_MPM_RNLO_30_D_SP_R1.sh',
#     'train_MPM_RNLO_30_D_SP_R2.sh',
#     'train_MPM_RNLO_30_D_SP_R3.sh',
#     'train_MPM_SN_30_D_SP_R1.sh',
#     'train_MPM_SN_30_D_SP_R2.sh',
#     'train_MPM_SN_30_D_SP_R3.sh',
#     'train_MPM_VN_30_D_SP_R1.sh',
#     'train_MPM_VN_30_D_SP_R2.sh',
#     'train_MPM_VN_30_D_SP_R3.sh',
#     # 'train_MPM_FW_30_D_SP_R1_seed10.sh',
#     # 'train_MPM_FW_30_D_SP_R2_seed10.sh',
#     # 'train_MPM_FW_30_D_SP_R3_seed10.sh',
#     # 'train_MPM_FW_30_D_SP_R1_seed144.sh',
#     # 'train_MPM_FW_30_D_SP_R2_seed144.sh',
#     # 'train_MPM_FW_30_D_SP_R3_seed144.sh',    
# ]

for name in bash_list:
    new_path = currt_path + '/scripts/' + name
    print("Going to run " + new_path)
    os.system("sbatch " + new_path)

print("Done")